### PR TITLE
#1 fix nonstandard property parsing

### LINKED ISSUE #1: Non-standard property forces parsing to fail
I'm using the library to parse an ical string from a google calendar public url, while doing so I'm facing some challenges. I'm sure that most of the problems are because either support for the newest spec is missing or google is doing non-standard things.

A property FILENAME on an attachment `ATTACH;FILENAME="Some video.mp4";FMTTYPE=video/mp4:https://drive.google.com/file/d/.../view?usp=drive_web`

Following your source, I've fixed this by using string replacement to change FILENAME to X-FILENAME. That at least gets me further into parsing. It would be nice to have a lenient parsing option, as someone using your library I just want to have the data parsed, whether the ical is 100% standards conforming bears no meaning on my goal to derive use out of the data there-in.

Second, I also hit a problem where a `x-...` property (correctly escaped by google) appears multiple times and thus is not converted into a list property automatically. The solution here would be to allow specifying what `X-` properties are list typed, always treating `X-` props as lists, or auto-converting to a list when multiple are present.

### PR DESCRIPTION
**Pull request by filecage**
Fixes #1 by no longer throwing for non-standard properties that are not prefixed with `X-` or `IANA-`

### CODE REVIEW

File: src/Parser/Properties/Property.ts [hunk 1]
```diff
@@ -2,10 +2,12 @@ export default abstract class Property<T = string, P extends {[key: string]: str
     public abstract readonly key: string;
     public readonly value: T;
     public readonly parameters: P;
+    public readonly isNonStandard: boolean;
 
-    constructor (value: T, parameters: P) {
+    constructor (value: T, parameters: P, isNonStandard: boolean = false) {
```
Comment (passionate-bram) [inline src/Parser/Properties/Property.ts:7]: There is a short-hand notation for constructors when the argument name matches the target field name.

https://www.typescriptlang.org/docs/handbook/2/classes.html#constructors

This constructor would be written as:

```ts
constructor (public readonly value: T, public readonly parameters: P, public readonly isNonStandard: boolean = false) {}
```

Some linters complain about the empty constructor body which you can solve with an `/* empty on purpose */` comment or similar.

Also note that in this case if there is additional logic besides the fields you can still have regular code in the constructor, the body executes after field assignments.

Comment (filecage) [reply src/Parser/Properties/Property.ts:7]: @passionate-bram Nice, I didn't know about constructor parameter promotion in TypeScript yet. I'll update this soon. Thanks for your help!
